"""
8-Puzzle solver: BFS vs DFS
SLE-2 Profiling experiment (02AML204)
"""

import time
import statistics
from collections import deque

GOAL = (1, 2, 3, 4, 5, 6, 7, 8, 0)

# A solvable, moderately hard start state (0 = blank)
# Generated by a 25-move random walk from the goal state so BFS and DFS
# show a clear, measurable difference (guideline: avoid puzzles that
# solve in < 1 ms).
START = (2, 0, 4,
         5, 6, 3,
         1, 7, 8)

MOVES = {
    0: [1, 3],       1: [0, 2, 4],       2: [1, 5],
    3: [0, 4, 6],    4: [1, 3, 5, 7],    5: [2, 4, 8],
    6: [3, 7],       7: [4, 6, 8],       8: [5, 7]
}


def neighbors(state):
    zero = state.index(0)
    for nxt in MOVES[zero]:
        new_state = list(state)
        new_state[zero], new_state[nxt] = new_state[nxt], new_state[zero]
        yield tuple(new_state)


def bfs(start, goal):
    frontier = deque([start])
    visited = {start}
    parent = {start: None}
    nodes_expanded = 0

    while frontier:
        state = frontier.popleft()
        nodes_expanded += 1
        if state == goal:
            path = []
            s = state
            while s is not None:
                path.append(s)
                s = parent[s]
            path.reverse()
            return path, nodes_expanded

        for nb in neighbors(state):
            if nb not in visited:
                visited.add(nb)
                parent[nb] = state
                frontier.append(nb)
    return None, nodes_expanded


def dfs(start, goal):
    # Iterative DFS (stack based) with a visited set so it terminates
    # on the finite 8-puzzle state graph.
    stack = [start]
    visited = {start}
    parent = {start: None}
    nodes_expanded = 0

    while stack:
        state = stack.pop()
        nodes_expanded += 1
        if state == goal:
            path = []
            s = state
            while s is not None:
                path.append(s)
                s = parent[s]
            path.reverse()
            return path, nodes_expanded

        for nb in neighbors(state):
            if nb not in visited:
                visited.add(nb)
                parent[nb] = state
                stack.append(nb)
    return None, nodes_expanded


def print_grid(state, label=""):
    if label:
        print(label)
    for r in range(3):
        row = state[r*3:(r+1)*3]
        print(" ".join(str(x) if x != 0 else "_" for x in row))
    print()


def run_experiment(runs=3):
    results = {"BFS": {"times": [], "nodes": None, "path_len": None},
               "DFS": {"times": [], "nodes": None, "path_len": None}}

    for algo_name, algo_fn in [("BFS", bfs), ("DFS", dfs)]:
        for i in range(runs):
            t0 = time.perf_counter()
            path, nodes = algo_fn(START, GOAL)
            t1 = time.perf_counter()
            elapsed_ms = (t1 - t0) * 1000
            results[algo_name]["times"].append(elapsed_ms)
            results[algo_name]["nodes"] = nodes
            results[algo_name]["path_len"] = (len(path) - 1) if path else None

    return results


if __name__ == "__main__":
    print_grid(START, "Initial State:")
    print_grid(GOAL, "Goal State:")

    results = run_experiment(runs=5)

    print("=" * 50)
    for algo in ["BFS", "DFS"]:
        times = results[algo]["times"]
        avg = statistics.mean(times)
        print(f"\n{algo} Results:")
        print(f"  Run times (ms): {[round(t, 3) for t in times]}")
        print(f"  Average time (ms): {avg:.4f}")
        print(f"  Nodes expanded: {results[algo]['nodes']}")
        print(f"  Solution length (moves): {results[algo]['path_len']}")

    import json
    with open("results.json", "w") as f:
        json.dump(results, f, indent=2)
